"""Add Mobile Field To User

Revision ID: 380be0a82a69
Revises: 02454d9f45ac
Create Date: 2023-01-12 09:23:55.780612

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '380be0a82a69'
down_revision = '02454d9f45ac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mobile', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('mobile')

    # ### end Alembic commands ###
