"""Add Resume Table

Revision ID: 5b807dca990d
Revises: 4133a206620f
Create Date: 2023-01-10 09:34:18.595322

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5b807dca990d'
down_revision = '4133a206620f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('resume',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('name', sa.String(length=20), nullable=True),
    sa.Column('slug', sa.String(length=50), nullable=True),
    sa.Column('layout_type', sa.String(length=50), nullable=True),
    sa.Column('module_order', sa.String(length=255), nullable=True),
    sa.Column('theme_color', sa.String(length=50), nullable=True),
    sa.Column('custom_styles', sa.JSON(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('resume')
    # ### end Alembic commands ###
