"""Add Education Table

Revision ID: 61069dc0d22d
Revises: 380be0a82a69
Create Date: 2023-01-30 15:40:13.833584

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '61069dc0d22d'
down_revision = '380be0a82a69'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('education',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('resume_id', sa.Integer(), nullable=True),
    sa.Column('label', sa.String(length=255), nullable=True),
    sa.Column('visible', sa.Boolean(), nullable=True),
    sa.Column('config', sa.JSON(), nullable=True),
    sa.Column('content_type', sa.String(length=50), nullable=True),
    sa.Column('show_split', sa.Boolean(), nullable=True),
    sa.Column('split', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['resume_id'], ['resume.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('education_detail',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('start_on', sa.String(length=255), nullable=True),
    sa.Column('end_on', sa.String(length=255), nullable=True),
    sa.Column('university_majors', sa.String(length=255), nullable=True),
    sa.Column('desc', sa.Text(), nullable=True),
    sa.Column('sort_index', sa.Float(), nullable=True),
    sa.Column('education_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['education_id'], ['education.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('education_detail')
    op.drop_table('education')
    # ### end Alembic commands ###
